config/routes.rb
Rails.application.routes.draw do
  resources :emps

end

app/models/emp.rb
class Emp < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/emps_controller.rb
class EmpsController < ApplicationController
  before_action :set_emp, only: [:show, :edit, :update, :destroy]

  # GET /emps
  # GET /emps.json
  def index
    @emps = Emp.all
  end

  # GET /emps/1
  # GET /emps/1.json
  def show
  end

  # GET /emps/new
  def new
    @emp = Emp.new
  end

  # GET /emps/1/edit
  def edit
  end

  # POST /emps
  # POST /emps.json
  def create
    @emp = Emp.new(emp_params)

    respond_to do |format|
      if @emp.save
        format.html { redirect_to @emp, notice: 'Emp was successfully created.' }
        format.json { render :show, status: :created, location: @emp }
      else
        format.html { render :new }
        format.json { render json: @emp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emps/1
  # PATCH/PUT /emps/1.json
  def update
    respond_to do |format|
      if @emp.update(emp_params)
        format.html { redirect_to @emp, notice: 'Emp was successfully updated.' }
        format.json { render :show, status: :ok, location: @emp }
      else
        format.html { render :edit }
        format.json { render json: @emp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emps/1
  # DELETE /emps/1.json
  def destroy
    @emp.destroy
    respond_to do |format|
      format.html { redirect_to emps_url, notice: 'Emp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emp
      @emp = Emp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emp_params
      params.require(:emp).permit(:name, :age, :address, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emps_helper.rb
module EmpsHelper
end

app/views/emps/_form.html.erb
<%= form_for(@emp) do |f| %>
  <% if @emp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@emp.errors.count, "error") %> prohibited this emp from being saved:</h2>

      <ul>
      <% @emp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/emps/edit.html.erb
<h1>Editing emp</h1>

<%= render 'form' %>

<%= link_to 'Show', @emp %> |
<%= link_to 'Back', emps_path %>

app/views/emps/index.html.erb
<h1>Listing emps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Address</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @emps.each do |emp| %>
      <tr>
        <td><%= emp.name %></td>
        <td><%= emp.age %></td>
        <td><%= emp.address %></td>
        <td><%= emp.email %></td>
        <td><%= link_to 'Show', emp %></td>
        <td><%= link_to 'Edit', edit_emp_path(emp) %></td>
        <td><%= link_to 'Destroy', emp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Emp', new_emp_path %>

app/views/emps/new.html.erb
<h1> This is kishore demo App </h1>
<h2>git push -u origin master</h2>
<h1>New emp</h1>

<%= render 'form' %>

<%= link_to 'Back', emps_path %>

app/views/emps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @emp.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @emp.age %>
</p>

<p>
  <strong>Address:</strong>
  <%= @emp.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @emp.email %>
</p>

<%= link_to 'Edit', edit_emp_path(@emp) %> |
<%= link_to 'Back', emps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Employee</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>